# Generated by Django 6.0.6 on 2026-06-28 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacationpackage',
            name='company',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='TravelCompany',
        ),
        migrations.DeleteModel(
            name='VacationPackage',
        ),
    ]
