# Generated by Django 6.0.6 on 2026-07-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paymob_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
