# Generated by Django 6.0.6 on 2026-07-04 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_paymob_order_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelcompany',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='Staff members who can manage this travel company.', related_name='managed_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
